* Audio Classification With Tags/Qualifiers:
This is a try at a tag/qualifier based classification system for audio. I use it
to organize my field recordings with help from an app called 'tagspaces'. Later
on, I can find recordings that match (or don't match) some set of
characteristics. As an example, I could get all my recordings that have
'envelopes with sharp attack, steady texture, a single sound source, and made
with solid objects' .

** Tag Groups
Note that the tags in the following tag groups indicate the presence of some trait /at some/ point or region in a
recording; recordings may be pretty long and varied with content.

*** PARALLELISM                                
Amount of [[https://www.sfu.ca/sonic-studio-webdav/handbook/Sound_Object.html][sound objects]] that occur at once.
- *singular:*  
  one sound object.
  may also include quasi singular sounds like traffic at a distance.
  e.g. guitar string pluck
- *compound:*  
  multiple distinct sound objects occuring to form an emergent sound object
  e.g. many pebbles hitting plastic, washing machine
- *parallel:*  
  multiple non-emergent objects or compound objects co-occuring (cafeteria, sidewalk ambience)
*** ENVELOPE                                      
See [[https://www.sfu.ca/sonic-studio-webdav/handbook/Envelope.html][envelope]]
The pattern in the overall intensity of the sound object.
E.g pebbles shuffling in hand [compound impulse]
- *stationary:*  
  intensity is consistent, see [[https://www.sfu.ca/sonic-studio-webdav/handbook/Stationary_Sound.html][stationary]]
- *impulse:*  
  sharp attack. see [[https://www.sfu.ca/sonic-studio-webdav/handbook/Impact_Sound.html][impulse]]
- *pulse:*  
  a short envelope, without a sharp attack
- *flux:*  
  gradual change in intensity, growth or decay 
  e.g waves
*** SPECTRUM                                         
- *broad:*  
  imperceptible dominant pitch
  e.g. gong, noise
  (adapted from Schaeffer's 'complex mass' qualifier)
- *tonal:*  
  perceptible dominant pitch
  e.g. guitar string
  (adapted from Schaeffer's 'tonal mass' qualifier)
- *moving:*  
  is the dominant band or pitch moving?
  e.g. siren
  (adapted from Schaeffer's 'varied mass' qualifier)

*** INTERNAL DYNAMICS                                 
The pattern in the intensity of the sustained part of a sound. See [[https://www.sfu.ca/sonic-studio-webdav/handbook/Internal_Dynamics.html][internal dynamics]]
- *granular:*  
  The sustained sound is made of [[https://www.sfu.ca/sonic-studio-webdav/handbook/Grain.html][grains]]
  e.g. a guiro
- *transients:*   
  The sustained sound has [[https://www.sfu.ca/sonic-studio-webdav/handbook/Transient.html][transients]] - sudden and brief fluctuation in
  a sound. 
  e.g. a record player that crackles
*** TEXTURE 
The qualitative feel of the sustained part of the sound
- *morphing:*   
- *steady:*   
- *rub:*   
- *vocal:*   
- *scrape:*   
- *diffuse:*   
- *pure:*   
- *buzz:*   
- *fizz:*   
- *hiss:*   
- *harsh:*   
- *warm:*   
- *energetic*:
*** OBJECT VARIANCE                                
Describes the variance of the qualities of [[https://www.sfu.ca/sonic-studio-webdav/handbook/Sound_Object.html][sound object]]'s across time. 
- *chaotic:*  
  e.g. IKEA food section, busy market square, 
- *varied:*  
  new sound objects succeed old ones with noticeably different qualities, but
  there is still structure
  e.g. voices on sidewalk of busy street, bird calls
- *nuanced:*  
  subtle, or no variation in qualities of successive sound objects
  e.g. hitting a dog bowl different ways
*** ELEMENT                                          
Elements involved in the production of the sound. This category helps me the most!
- *fire:*  
  A non-kinetic process, like a chemical reaction, or electricity 
  e.g. broken light, radio static
- *earth:*  
  Solids.
  e.g. exciting an object with another one, rustling leaves, plucking a string
- *air:*  
  Gas.
  e.g. wind, horns, whistles
- *water:*  
  Liquid.
  e.g. water stream

** Examples
- cafeteria ambience[parallel stationary air earth chaotic]
- birds in forest[compound pulse tonal vocal varied]
- dog bark[singular pulse broad vocal]
- xylophone mallet hit[singular impulse flux tonal steady pure earth]
- radio static voices[compound stationary pulse broad tonal transients vocal hiss morphing chaotic fire]
- blown bottle top[compound stationary tonal hiss steady air earth]
- electric saw on wood[compound stationary broad moving granular morphing
  buzz hiss harsh energetic nuanced fire earth]
** References
My main source was this [[https://www.sfu.ca/sonic-studio-webdav/handbook/index.html][handbook]].
